### ISSUE TITLE
Support `list.fields`

### ISSUE THREAD

**Issue by myConsciousness** [twitter-dart/twitter-api-v2#186]
# 1. Problem to solve

enum (created_at, follower_count, member_count, private, description, owner_id)

- [ ] [GET /2/users/:id/followed_lists](https://developer.twitter.com/en/docs/twitter-api/lists/list-follows/api-reference/get-users-id-followed_lists)
- [ ] [GET /2/lists/:id](https://developer.twitter.com/en/docs/twitter-api/lists/list-lookup/api-reference/get-lists-id)
- [ ] [GET /2/users/:id/owned_lists](https://developer.twitter.com/en/docs/twitter-api/lists/list-lookup/api-reference/get-users-id-owned_lists)
- [ ] [GET /2/users/:id/list_memberships](https://developer.twitter.com/en/docs/twitter-api/lists/list-members/api-reference/get-users-id-list_memberships)
- [ ] [GET /2/users/:id/pinned_lists](https://developer.twitter.com/en/docs/twitter-api/lists/pinned-lists/api-reference/get-users-id-pinned_lists)

# 2. Proposal

# 3. More information

**Comment by niteshsh4rma** [comment]
@myConsciousness Can I work on this?

**Comment by myConsciousness** [comment]
> @myConsciousness Can I work on this?

Yes of course, you can take `media.fields` and `topic.fields` too :)
