### ISSUE TITLE
Support `variant` field for `MediaData`

### ISSUE THREAD

**Issue by myConsciousness** [twitter-dart/twitter-api-v2#265]
# 1. What could be improved

# 2. Why should this be improved

# 3. Any risks?

# 4. More information

https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/media

**Comment by guomouren** [comment]
Can you add this field first when you haven't figured out how to improve it ?

**Comment by myConsciousness** [comment]
Hi @guomouren ,

I couldn't understand what you want to know, but this is a note of a field I found while reading the official documentation :)

**Comment by guomouren** [comment]
I can't find variant in media_field.dart. I can't get video related information

**Comment by myConsciousness** [comment]
@guomouren 

Of course because no one implemented it yet haha, I'm involved in multiple projects and don't have time to worry about the details of an issue 😏

If you can create a pull request about this field, I'll review and merge it :)

**Comment by niteshsh4rma** [comment]
@myConsciousness Please assign me this :)

**Comment by myConsciousness** [comment]
Hi @guomouren , the `variant` field in `MediaData` will be available in the next release :)
