### ISSUE TITLE
UnauthorizedException when creating a tweet

### ISSUE THREAD

**Issue by VinniciusJesus** [twitter-dart/twitter-api-v2#404]
Flutter 3.0.5

I'm facing this this one when trying to create a tweet which means invalid access token.

But my access token is coming directly from the `twitter_oauth2_pkce` library

When I use the access token that is already in my twitter developer portal, the library works as expected...

code sample

     ` final oauth2 = TwitterOAuth2Client(
      clientId: 'xxxxxxxxxxxxxxxxxxxxxxxx',
      clientSecret: 'xxxxxxxxxxxxxxxxxxxxxxxx',
      redirectUri: 'org.example.android.oauth://callback/',
      customUriScheme: 'org.example.android.oauth',
    );

    final response =
        await oauth2.executeAuthCodeFlowWithPKCE(scopes: Scope.values);

    print("Acess token " + response.accessToken);

    final twitter = v2.TwitterApi(
      oauthTokens: v2.OAuthTokens(
          consumerKey: "xxxxxxxxxxxxxxxxxxxxxxxx",
          consumerSecret: "xxxxxxxxxxxxxxxxxxxxxxxx",
          accessToken: response.accessToken,
          accessTokenSecret: "xxxxxxxxxxxxxxxxxxxxxxxx"),
      bearerToken:   'xxxxxxxxxxxxxxxxxxxxxxxx',
        
    );

    await twitter.tweetsService.createTweet(
      text: 'Hello World!',
    );`

Sorry for my bad english

**Comment by myConsciousness** [comment]
Hi @VinniciusJesus , thanks for using this package!

Access token from `twitter_oauth2_pkce` is **bearer token**, and not access token of OAuth 1.0a. Also, you don't need to specify `OAuthTokens` if you can use OAuth 2.0 PKCE, because bearer token has all scopes you specified.

So your code should be fixed like below:

```dart
final oauth2 = TwitterOAuth2Client(
  clientId: 'xxxxxxxxxxxxxxxxxxxxxxxx',
  clientSecret: 'xxxxxxxxxxxxxxxxxxxxxxxx',
  redirectUri: 'org.example.android.oauth://callback/',
  customUriScheme: 'org.example.android.oauth',
);

final response =
    await oauth2.executeAuthCodeFlowWithPKCE(scopes: Scope.values);

print("Acess token " + response.accessToken);

final twitter = v2.TwitterApi(
  bearerToken:   response.accessToken,
);

await twitter.tweetsService.createTweet(
  text: 'Hello World!',
);
```

**Comment by VinniciusJesus** [comment]
Thank you for your help! Closing issue...
