### ISSUE TITLE
Unhandled Exception: CheckedFromJsonException Could not create `_$_OrganicTweetMetrics`

### ISSUE THREAD

**Issue by VinniciusJesus** [twitter-dart/twitter-api-v2#407]
Flutter: 3.0.5
Package: 3.0.2

When Requesting Organic Metrics in `lookupTweets()` I get this error

`[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: CheckedFromJsonException
Could not create `_$_OrganicTweetMetrics`.
There is a problem with "url_link_clicks".
type 'Null' is not a subtype of type 'int' in type cast`

The same error happens when using privateMetrics 

Code sample:

```js
final twitter = TwitterApi(
        bearerToken: _store.twitterAccessToken,
      );

      user = await twitter.usersService.lookupMe(
        expansions: [
          UserExpansion.pinnedTweetId,
        ],
        userFields: [
          UserField.createdAt,
          UserField.location,
          UserField.publicMetrics,
          UserField.url,
          UserField.entities,
          UserField.id,
          UserField.pinnedTweetId,
        ],
      );

      tweets = await twitter.tweetsService.lookupTweets(
        userId: user!.data.id,
        tweetFields: [
          TweetField.organicMetrics,
          // TweetField.privateMetrics,
          TweetField.publicMetrics,
          TweetField.createdAt,
          TweetField.text,
        ],
      );
```

**Comment by myConsciousness** [comment]
Hi @VinniciusJesus , thanks for your report! :)

My recollection when I implemented this feature was that the `url_link_clicks` field was always set and returned by Twitter, but apparently it is not returned now, or maybe it has been officially removed.

We can fix this immediately by making this field nullable in this package, but please wait a little longer as we need to make sure that this field itself is valid :)

**Comment by myConsciousness** [comment]
Hi @VinniciusJesus 

I have checked that the `url_link_clicks` field is only set if the number is greater than 0. It's a strange spec, but it seems to be set to null if the count is 0.

Are you interested in create a pull request about this issue? If interested, please create a PR with the following modifications :)

- **organic_tweet_metrics.dart**
- **private_tweet_metrics.dart**
- **promoted_tweet_metrics.dart**

And fix field:

**From**

```dart
@JsonKey(name: 'url_link_clicks') required int linkClickCount,
```

**To**

```dart
@JsonKey(name: 'url_link_clicks') int? linkClickCount,
```

Then please execute below commands in terminal:

1. `dart pub upgrade`
2. `dart pub run build_runner build`

Let me know if there is something wrong :)
