### ISSUE TITLE
Support `POST media/subtitles/create`

### ISSUE THREAD

**Issue by myConsciousness** [twitter-dart/twitter-api-v2#437]
# 1. Problem to solve

https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/api-reference/post-media-subtitles-create

# 2. Proposal

# 3. More information

**Comment by niteshsh4rma** [comment]
Hi @myConsciousness, can you assign me this.

**Comment by myConsciousness** [comment]
Twitter always returns `503` status and following error when we try to tweet with subtitled video.

```json
{
   "title":"Service Unavailable",
   "detail":"Service Unavailable",
   "type":"about:blank",
   "status":503
}
```

We need to check what it is before release.

https://twittercommunity.com/t/video-with-subtitles-uploaded-in-v1-1-cannot-be-tweeted-from-v2-endpoint/179407

**Comment by myConsciousness** [comment]
There is a file validation for `.srt`.

It's possible to tweet with valid video and `.srt` files.

https://twittercommunity.com/t/video-with-subtitles-uploaded-in-v1-1-cannot-be-tweeted-from-v2-endpoint/179407/6
