### ISSUE TITLE
Support `/1.1/geo/reverse_geocode`

### ISSUE THREAD

**Issue by myConsciousness** [twitter-dart/twitter-api-v2#584]
@myConsciousness 

Thanks for your work.

Can I use `/1.1/geo/reverse_geocode` here?

I am trying 

```
final res = await api.geo.searchLocations(
            granularity: GeoGranularity.neighborhood,
            latitude:****,
            longitude: ******,
          );
```

but I got

```
[埼玉 所沢市, 埼玉 川越市, 埼玉 さいたま市 大宮区,....
```

It is too broad, I just want to search for the store that is near me.

_Originally posted by @normidar in https://github.com/twitter-dart/twitter-api-v2/issues/577#issuecomment-1336127034_

**Comment by myConsciousness** [comment]
Hi @normidar , thanks for your feedback :)

Unfortunately, the current implementation does not support the `/1.1/geo/reverse_geocode` endpoint. This could have been added in the last release, but I could not determine the demand for an endpoint that does reverse geocoding.

However, this endpoint would be very easy to add. I'm looking forward to your pull request! :)

**Comment by normidar** [comment]
I created PR!

**Comment by myConsciousness** [comment]
@all-contributors please add @normidar for code, doc, question
