### ISSUE TITLE
Support fetching a user's profile banner

### ISSUE THREAD

**Issue by jordyvandomselaar** [twitter-dart/twitter-api-v2#590]
# 1. Problem to solve

It's currently not possible to fetch a user's profile banner.

# 2. Proposal

Unfortunately, there is no v2 endpoint to fetch the user's profile banner, but there are multiple v1 endpoints we can use.

- https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/manage-account-settings/api-reference/get-users-profile_banner
    - Requires using an access token and secret per https://twittercommunity.com/t/how-to-get-banner-url-for-a-user/168692/7
- https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-users-show
    - Works with bearer token per https://twittercommunity.com/t/how-to-get-banner-url-for-a-user/168692/7

I haven't tested those calls, will need some work.

# 3. More information

- Yes, I'd be willing to work on a PR for this =)

**Comment by myConsciousness** [comment]
Hi @jordyvandomselaar , thanks for your feedback :)

I also have been waiting for some time for these v1.1 endpoints to be supported as v2.0, but it seems that official Twitter no longer has the time to devote to the Twitter API.

I'm in favor of implementing these endpoints, but the `users/show` endpoint seems difficult to map to the v2 User object format. However, the `users/profile_banner` endpoint could easily be implemented by creating a new object :)

Are you interested in creating a pull request? Let's implement `users/profile_banner` at first :)

**Comment by myConsciousness** [comment]
@jordyvandomselaar ,

If you have any questions about creating a pull request, please do not hesitate to let me know :)

My guess is that this endpoint should be implemented within `UsersService`. 

- https://pub.dev/documentation/twitter_api_v2/latest/twitter_api_v2/UsersService-class.html

And please refer to `GeoService` and `TrendsService` as a way to implement v1.1 endpoints :)

- https://pub.dev/documentation/twitter_api_v2/latest/twitter_api_v2/GeoService-class.html
- https://pub.dev/documentation/twitter_api_v2/latest/twitter_api_v2/TrendsService-class.html
