### ISSUE TITLE
Is the scheduled tweets end points supported?

### ISSUE THREAD

**Issue by tomtaila** [twitter-dart/twitter-api-v2#660]
It doesn't look like this supports the following:

https://developer.twitter.com/en/docs/twitter-ads-api/creatives/guides/scheduled-tweets-guide

Would you like me to make a PR for this?

**Comment by myConsciousness** [comment]
Hi @tomtaila,

This endpoint is not Twitter API v2.0, but Twitter Ads API. So this endpoint is not compatible with this package.

**Comment by tomtaila** [comment]
Gotcha! Great work btw :) 🥂

**Comment by myConsciousness** [comment]
@tomtaila ,

And thanks for feedback! :)
