### ISSUE TITLE
How can I create a tweet with attached image?

### ISSUE THREAD

**Issue by plztrial4me** [twitter-dart/twitter-api-v2#90]
How can I create a tweet with attached image?

**Comment by myConsciousness** [comment]
Hi @plztrial4me !

I'm currently in the process of implementing basic functionality for each endpoint, so I'm not yet able to support tweets with images. 

However, I know that this feature is in very high demand and I will make it as high a priority as possible in my development :) So please wait for next releases, or you can create a pull request if you want to contribute!

**Comment by myConsciousness** [comment]
## Memo

The official `Twitter API v2.0` **does not** currently support `Media Endpoint`. 

Therefore, one possible approach would be to upload images using the `Twitter API v1.1` Media Endpoint and use the `id` of the uploaded image in the `Twitter API v2.0` endpoint. But this library does not support the v1.1 implementation, so I would like to avoid this way.

The policy for this library is to implement the ability to POST images that have already been uploaded from the `tweetsService.createTweet`, and wait for the official Twitter API v2.0 to support `Media Endpoint` for image uploading.

**Comment by AaronDQQ** [comment]
Is it possible to share Image to Twitter now? @myConsciousness
